### ISSUE TITLE
Is `updatevars!(prob)` required at every time-step?

### ISSUE THREAD

**Issue by navidcy** [MHDFlows/MHDFlows#1]
If the problem's state is `prob.sol` then all the information to time-step the problem is there. Or am I missing something?

https://github.com/MHDFlows/MHDFlows.jl/blob/ad7ed6fbe5e8fb3e99157bd7be16275c7008f4ea/src/integrator.jl#L85

**Comment by doraemonho** [comment]
I think this line of code is a relic from the early development stage.
The `updatevars!` is not necessary and they will not affect the result of the solution update. 
Let me run a set of examples for testing to confirm it. 
This probably should be removed for the next version update.

**Comment by navidcy** [comment]
I should affect speed and allocations though.

**Comment by doraemonho** [comment]
> I should affect speed and allocations though.

I agree but this depends on the ODE method you are using.
I ran a profile check before. If you are using the RK4 method (the Euler method is not always stable), most of the time (~90%) the code is spent inside the `BᵢUpdate`/`UᵢUpdate` function.

**Comment by doraemonho** [comment]
Version 0.1.1 Released #2 and issue has been resolved
